#!/bin/bash
set -e
set -v

DTGROOT=$(pwd)
SD=$1

export DEVICE=oga

export ARCH=arm64
export CROSS_COMPILE=aarch64-linux-gnu-

mkdir -p tmp

printf 'o
n
p
1
2048
+4G
n
p
2


w
' | fdisk $SD || true
partx $SD
# system partition
mkfs.ext4 ${SD}1
# data partition
mkfs.fat -F32 ${SD}2

mkdir -p $DTGROOT/tmp/root
mkdir -p $DTGROOT/tmp/data
mount ${SD}1 $DTGROOT/tmp/root
mount ${SD}2 $DTGROOT/tmp/data

./kernel/build $DTGROOT $DEVICE $SD
./uboot/build $DTGROOT $DEVICE $SD
./fs/build $DTGROOT $DEVICE $SD
./fs/mk_data $DTGROOT $DEVICE $SD

./kernel/install $DTGROOT $DEVICE $SD
./uboot/install $DTGROOT $DEVICE $SD


umount $DTGROOT/tmp/data

$DTGROOT/tmp/root/destroy -r

sync

echo 'Done!'
