#!/bin/bash
set -e

export DTGROOT=$1
export DEVICE=$2
export SD=$3

export ARCH=arm64
export CROSS_COMPILE=aarch64-linux-gnu-

mkdir -p $DTGROOT/tmp
cd $DTGROOT/tmp

#if [ -d 'linux' ]; then
#	cd linux
#	git pull
#else
#	git clone https://github.com/Maccraft123/linux --single-branch -b mac/go-next
#fi

cd $DTGROOT/tmp/linux

cp $DTGROOT/device/$DEVICE/linux-config ./.config

patch -p1 < $DTGROOT/device/$DEVICE/gadget.patch

make oldconfig
make -j$(nproc)

cp drivers/usb/dwc2/dwc2.ko ./dwc2-gadget.ko

patch -p1 -R < $DTGROOT/device/$DEVICE/gadget.patch

make oldconfig
make -j$(nproc)
