#!/bin/bash
set -e

export DTGROOT=$1
export DEVICE=$2
export SD=$3

mkdir -p $DTGROOT/tmp
cd $DTGROOT/tmp

if [ -d 'linux' ]; then
	cd linux
	git pull
else
	git clone https://github.com/Maccraft123/linux --single-branch -b odroidgo
fi

cd $DTGROOT/tmp/linux

cp $DTGROOT/device/$DEVICE/linux-config.gadget ./.config
make oldconfig
make -j$(nproc)
cp drivers/usb/dwc2/dwc2.ko ./dwc2-gadget.ko

cp $DTGROOT/device/$DEVICE/linux-config ./.config

make oldconfig
make -j$(nproc)
