#!/bin/bash
set -e

export DTGROOT=$1
export DEVICE=$2
export SD=$3

mkdir -p $DTGROOT/tmp
cd $DTGROOT/tmp


#chroot $DTGROOT/tmp/root /bin/passwd -d root
#chroot $DTGROOT/tmp/root /bin/apt install -y sway xfce4-terminal xwayland i3status build-essential git libncurses-dev supertuxkart retroarch kodi kodi-peripheral-joystick brightnessctl sudo alsa-utils
#chroot $DTGROOT/tmp/root /bin/apt install -y libretro-nestopia libretro-mupen64plus libretro-mgba libretro-gambatte libretro-desmume libretro-beetle-psx libretro-bsnes-mercury-performance 

#[ -f ArchLinuxARM-aarch64-latest.tar.gz ] && rm -f ArchLinuxARM-aarch64-latest.tar.gz
#wget http://os.archlinuxarm.org/os/ArchLinuxARM-aarch64-latest.tar.gz
#bsdtar -xpf ArchLinuxARM-aarch64-latest.tar.gz -C $DTGROOT/tmp/root

rm -f $DTGROOT/tmp/root/etc/resolv.conf
cat /etc/resolv.conf > $DTGROOT/tmp/root/etc/resolv.conf

#rm -rf $DTGROOT/tmp/root/etc/pacman.d/gnupg

#arch-chroot $DTGROOT/tmp/root /bin/pacman-key --init
#arch-chroot $DTGROOT/tmp/root /bin/pacman-key --populate archlinuxarm

sed -i'' 's/CheckSpace/#CheckSpace/' $DTGROOT/tmp/root/etc/pacman.conf
sed -i'' 's/SigLevel    = Required DatabaseOptional/SigLevel = Never/' $DTGROOT/tmp/root/etc/pacman.conf # who needs security anyways

arch-chroot $DTGROOT/tmp/root /bin/pacman -Syu mesa sway xfce4-terminal xorg-xwayland i3status gcc git ncurses retroarch brightnessctl sudo alsa-utils make 
arch-chroot $DTGROOT/tmp/root /bin/pacman -Rsc linux-aarch64

chroot $DTGROOT/tmp/root /usr/sbin/useradd -c "DTG User" -m user -G video,audio,render,input -s /bin/bash

mkdir -p $DTGROOT/tmp/root/etc/systemd/system/getty@tty1.service.d/
printf '[Service]
ExecStart=
ExecStart=-/usr/sbin/agetty --autologin user --noclear %%I $TERM
' > $DTGROOT/tmp/root/etc/systemd/system/getty@tty1.service.d/override.conf

echo 'export WLR_LIBINPUT_NO_DEVICES=1' >> $DTGROOT/tmp/root/home/user/.bashrc
echo 'tty | grep tty1 && exec sway' >> $DTGROOT/tmp/root/home/user/.bashrc
echo '[ -n "$DISPLAY" ] && ( while true; do dtg-launcher; done )' >> $DTGROOT/tmp/root/home/user/.bashrc

cp $DTGROOT/device/$DEVICE/sway-config $DTGROOT/tmp/root/etc/sway/config
cp $DTGROOT/device/$DEVICE/i3status.conf $DTGROOT/tmp/root/etc/i3status.conf

# todo: odroid go advance
cp $DTGROOT/device/$DEVICE/retroarch.cfg $DTGROOT/tmp/root/etc/retroarch.cfg

mkdir -p $DTGROOT/tmp/root/dtg-ng/programs
cp -r $DTGROOT/programs/* $DTGROOT/tmp/root/dtg-ng/programs/

chmod a+x $DTGROOT/tmp/root/dtg-ng/programs/dtg-launcher/install
chroot $DTGROOT/tmp/root/ /dtg-ng/programs/dtg-launcher/install

chmod a+w $DTGROOT/tmp/root/etc/sudoers
echo 'user ALL=(ALL:ALL) NOPASSWD: ALL' >> $DTGROOT/tmp/root/etc/sudoers
chmod a-w $DTGROOT/tmp/root/etc/sudoers


mkdir $DTGROOT/tmp/root/data
echo '/dev/mmcblk0p2 /data vfat rw,umask=0000 0 0' > $DTGROOT/tmp/root/etc/fstab
