#!/bin/bash
set -e

export DTGROOT=$1
export DEVICE=$2
export SD=$3

mkdir -p $DTGROOT/tmp
cd $DTGROOT/tmp

debootstrap --arch=arm64 sid $DTGROOT/tmp/root https://deb.debian.org/debian || true


chroot $DTGROOT/tmp/root /bin/passwd -d root
chroot $DTGROOT/tmp/root /bin/apt update
chroot $DTGROOT/tmp/root /bin/apt install -y sway xfce4-terminal xwayland i3status build-essential git libncurses-dev supertuxkart retroarch kodi kodi-peripheral-joystick brightnessctl sudo alsa-utils
chroot $DTGROOT/tmp/root /usr/sbin/useradd -c "DTG User" -m user -G video,audio,render,input -s /bin/bash

mkdir -p $DTGROOT/tmp/root/etc/systemd/system/getty@tty1.service.d/
printf '[Service]
ExecStart=
ExecStart=-/usr/sbin/agetty --autologin user --noclear %%I $TERM
' > $DTGROOT/tmp/root/etc/systemd/system/getty@tty1.service.d/override.conf

echo 'export WLR_LIBINPUT_NO_DEVICES=1' >> $DTGROOT/tmp/root/home/user/.bashrc
echo 'tty | grep tty1 && exec sway' >> $DTGROOT/tmp/root/home/user/.bashrc
echo '[ -n "$DISPLAY" ] && ( while true; do dtg-launcher; done )' >> $DTGROOT/tmp/root/home/user/.bashrc

cp $DTGROOT/device/$DEVICE/sway-config $DTGROOT/tmp/root/etc/sway/config
cp $DTGROOT/device/$DEVICE/i3status.conf $DTGROOT/tmp/root/etc/i3status.conf

# todo: odroid go advance
cp $DTGROOT/device/$DEVICE/retroarch.cfg $DTGROOT/tmp/root/etc/retroarch.cfg

mkdir -p $DTGROOT/tmp/root/dtg-ng/programs
cp -r $DTGROOT/programs/* $DTGROOT/tmp/root/dtg-ng/programs/

chmod a+x $DTGROOT/tmp/root/dtg-ng/programs/dtg-launcher/install
chroot $DTGROOT/tmp/root/ /dtg-ng/programs/dtg-launcher/install

# make power key suspend
sed -i'' 's/#HandlePowerKey=poweroff/HandlePowerKey=suspend/' $DTGROOT/tmp/root/etc/systemd/logind.conf
