#!/bin/bash
set -e

export DTGROOT=$1
export DEVICE=$2
export SD=$3

mkdir -p $DTGROOT/tmp
cd $DTGROOT/tmp


#chroot $DTGROOT/tmp/root /bin/passwd -d root
#chroot $DTGROOT/tmp/root /bin/apt install -y sway xfce4-terminal xwayland i3status build-essential git libncurses-dev supertuxkart retroarch kodi kodi-peripheral-joystick brightnessctl sudo alsa-utils
#chroot $DTGROOT/tmp/root /bin/apt install -y libretro-nestopia libretro-mupen64plus libretro-mgba libretro-gambatte libretro-desmume libretro-beetle-psx libretro-bsnes-mercury-performance


ROOTFS_TAR="$(curl -s -L https://voidlinux.org/download/ | grep aarch64 | tr '"' ' ' | awk '{print $3}' | grep -v musl)"

wget $ROOTFS_TAR -O void.tar.xz
tar xfp void.tar.xz -C $DTGROOT/tmp/root
cp /etc/resolv.conf $DTGROOT/tmp/root/etc/resolv.conf

chroot $DTGROOT/tmp/root/ /bin/xbps-install -Syu xbps
chroot $DTGROOT/tmp/root/ /bin/xbps-install -yu
chroot $DTGROOT/tmp/root/ /bin/xbps-install -y base-system
chroot $DTGROOT/tmp/root/ /bin/xbps-remove -y base-voidstrap
chroot $DTGROOT/tmp/root/ /bin/xbps-install -y vim NetworkManager mesa mesa-panfrost-dri base-devel sway xfce4-terminal xorg-server-xwayland i3status git ncurses supertuxkart retroarch kodi kodi-addon-peripheral-joystick brightnessctl sudo alsa-utils ppsspp ncurses-devel dejavu-fonts-ttf

chroot $DTGROOT/tmp/root /usr/sbin/useradd -c "DTG User" -m user -G video,audio,input -s /bin/bash

cp -R $DTGROOT/tmp/root/etc/sv/agetty-tty1 $DTGROOT/tmp/root/etc/sv/agetty-autologin-tty1
echo 'GETTY_ARGS="--autologin user --noclear"
BAUD_RATE=38400
TERM_NAME=linux' > $DTGROOT/tmp/root/etc/sv/agetty-autologin-tty1/conf

[ -e $DTGROOT/tmp/root/etc/runit/runsvdir/default/agetty-tty1 ] && rm -rf $DTGROOT/tmp/root/etc/runit/runsvdir/default/agetty-tty1
[ -e $DTGROOT/tmp/root/etc/runit/runsvdir/default/agetty-autologin-tty1 ] && rm -rf $DTGROOT/tmp/root/etc/runit/runsvdir/default/agetty-autologin-tty1
# symlinks have to be made inside chrot
chroot $DTGROOT/tmp/root ln -s /etc/sv/agetty-autologin-tty1 /etc/runit/runsvdir/default/

# the uart thing shell
cp -R $DTGROOT/tmp/root/etc/sv/agetty-ttyS0 $DTGROOT/tmp/root/etc/sv/agetty-ttyS2
chroot $DTGROOT/tmp/root ln -s /etc/sv/agetty-ttyS2 /etc/runit/runsvdir/default/

chroot $DTGROOT/tmp/root /bin/passwd -d root

echo 'export WLR_LIBINPUT_NO_DEVICES=1' >> $DTGROOT/tmp/root/home/user/.bashrc
echo 'tty | grep tty1 && exec sway' >> $DTGROOT/tmp/root/home/user/.bashrc
echo '[ -n "$WAYLAND_DISPLAY" ] && ( while true; do dtg-launcher; done )' >> $DTGROOT/tmp/root/home/user/.bashrc

cp $DTGROOT/device/$DEVICE/sway-config $DTGROOT/tmp/root/etc/sway/config
cp $DTGROOT/device/$DEVICE/i3status.conf $DTGROOT/tmp/root/etc/i3status.conf

# todo: odroid go advance
cp $DTGROOT/device/$DEVICE/retroarch.cfg $DTGROOT/tmp/root/etc/retroarch.cfg

mkdir -p $DTGROOT/tmp/root/dtg-ng/programs
cp -r $DTGROOT/programs/* $DTGROOT/tmp/root/dtg-ng/programs/

chmod a+x $DTGROOT/tmp/root/dtg-ng/programs/dtg-launcher/install
chmod a+x $DTGROOT/tmp/root/dtg-ng/programs/dtg-stats/install
chroot $DTGROOT/tmp/root/ /dtg-ng/programs/dtg-launcher/install
chroot $DTGROOT/tmp/root/ /dtg-ng/programs/dtg-stats/install

chmod a+w $DTGROOT/tmp/root/etc/sudoers
echo 'user ALL=(ALL:ALL) NOPASSWD: ALL' >> $DTGROOT/tmp/root/etc/sudoers
chmod a-w $DTGROOT/tmp/root/etc/sudoers

mkdir $DTGROOT/tmp/root/data
echo '/dev/mmcblk0p2 /data vfat rw,umask=0000 0 0' > $DTGROOT/tmp/root/etc/fstab
echo 'tmpfs /tmp tmpfs defaults,nosuid,nodev 0 0' >> $DTGROOT/tmp/root/etc/fstab
