#!/bin/bash

# this runs on device or in chroot
# updates too

mkdir -p /dtg-ng/src
cd /dtg-ng/src

if [ -d dtg-launcher ]; then
	cd dtg-launcher
	git pull
else
	git clone https://github.com/Maccraft123/dtg-launcher.git
	cd dtg-launcher
fi

make
make install
