#!/bin/bash

DTGROOT=$1

cd $DTGROOT/tmp/mesa

echo "export LIBGL_DRIVERS_PATH='/opt/lib/aarch64-linux-gnu/dri/:/usr/lib/aarch64-linux-gnu/dri:\$LIBGL_DRIVERS_PATH'" >> $DTGROOT/tmp/root/etc/profile
echo "export LD_LIBRARY_PATH=/opt/lib/aarch64-linux-gnu/:\$LD_LIBRARY_PATH" >> $DTGROOT/tmp/root/etc/profile

touch $DTGROOT/tmp/root/etc/ld.so.conf.d/0-mesa.conf
echo "/opt/lib/aarch64-linux-gnu" > $DTGROOT/tmp/root/etc/ld.so.conf.d/0-mesa.conf

DESTDIR=$DTGROOT/tmp/root/ ninja -C dtg-build install
chroot $DTGROOT/tmp/root/ ldconfig

ldconfig
