#!/bin/bash

DTGROOT=$1

cd $DTGROOT/tmp/mesa

if grep -s LIBGL_DRIVERS_PATH $DTGROOT/tmp/root/etc/profile; then
	echo "export LIBGL_DRIVERS_PATH=/opt/lib/aarch64-linux-gnu/dri/" >> $DTGROOT/tmp/root/etc/profile
	echo "export LD_LIBRARY_PATH=/opt/lib/aarch64-linux-gnu/" >> $DTGROOT/tmp/root/etc/profile
else
	echo AAAAAAA
fi

touch $DTGROOT/tmp/root/etc/ld.so.conf.d/0-mesa.conf
echo "/opt/lib/aarch64-linux-gnu" > $DTGROOT/tmp/root/etc/ld.so.conf.d/0-mesa.conf

DESTDIR=$DTGROOT/tmp/root/ ninja -C dtg-build install
chroot $DTGROOT/tmp/root/ ldconfig

ldconfig
